package com.cliniqo.common.enums;

public enum AuditEventType {
    AUTH_LOGIN_SUCCESS,
    AUTH_LOGIN_FAILURE,
    AUTH_LOGOUT,
    REFRESH_ROTATED,
    REFRESH_REUSE_DETECTED,
    TENANT_TAMPER,
    SUPER_ADMIN_TARGET_CONTEXT,
    SOFT_DELETE,
    SECURITY_VALIDATION_FAILURE,
    TEST_MUTATION
}
