package com.cliniqo.common.enums;

public enum AuditEventType {
    AUTH_LOGIN_SUCCESS,
    AUTH_LOGIN_FAILURE,
    AUTH_LOGOUT,
    REFRESH_ROTATED,
    REFRESH_REUSE_DETECTED,
    TENANT_TAMPER,
    SUPER_ADMIN_TARGET_CONTEXT,
    BOOTSTRAP_SUPER_ADMIN_AVAILABLE,
    BOOTSTRAP_SUPER_ADMIN_SKIPPED,
    SUPER_ADMIN_ONBOARDING_SUBMITTED,
    CLINIC_ONBOARDING_SUCCEEDED,
    CLINIC_ONBOARDING_FAILED,
    CLINIC_CREATED,
    FIRST_CLINIC_ADMIN_CREATED,
    DEFAULT_PERMISSIONS_ASSIGNED,
    PUBLIC_WEBSITE_SLUG_RESERVED,
    WHATSAPP_METADATA_CAPTURED,
    TEMPORARY_CREDENTIAL_ISSUED,
    CLINIC_DEACTIVATED,
    CLINIC_REFRESH_SESSIONS_REVOKED,
    CLINIC_USER_SUPER_ADMIN_ELEVATION_REJECTED,
    SOFT_DELETE,
    SECURITY_VALIDATION_FAILURE,
    TEST_MUTATION
}
